version: "3.8"
services:
  backend:
      image: "gcsecommerceapp-backend:latest"
      restart: always
      build: ../.
#        context: ../..
      container_name: app
      ports:
        - "8080:8080"
      depends_on:
          - db
  db:
    platform: linux/x86_64
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: ecommerceapp
      MYSQL_ROOT_PASSWORD: ecommerceapp
    volumes:
#      - ./db-data/:/var/lib/mysql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql